// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/qx66/camp/internal/biz"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func initApp(logger *zap.Logger) *iApp {
	dnsClientInspectUseCase := biz.NewDnsClientInspectUseCase(logger)
	httpInspectClientUseCase := biz.NewHttpInspectClientUseCase(logger)
	icmpClientUseCase := biz.NewIcmpClientUseCase(logger)
	socketClientUseCase := biz.NewSocketClientUseCase(logger)
	chromeDpClientUseCase := biz.NewChromeDpClientUseCase(logger)
	webSocketUseCase := biz.NewWebSocketUseCase(logger, dnsClientInspectUseCase, httpInspectClientUseCase, icmpClientUseCase, socketClientUseCase, chromeDpClientUseCase)
	mainIApp := newIApp(logger, webSocketUseCase)
	return mainIApp
}
